### ISSUE TITLE
 real time set

### ISSUE THREAD

**Issue by eugenpar** [tiagoCuervo/FuzzyTensor#4]
Hi! Perhaps there is a version with a real time set at the input? Evgeniy

**Comment by tiagoCuervo** [comment]
Hi! I'm sorry, I'm not sure I understand what you mean with "a real time set at the input", maybe you are talking about some real data instead of a generated time series?

**Comment by eugenpar** [comment]
Hi! This refers to the Forex market data

**Comment by tiagoCuervo** [comment]
Well, in which format do you have your data? Do you pull it from an API? Do you have a text file?

**Comment by eugenpar** [comment]
This is a text file in csv format. commas can be used as indicator separators, and semicolons can be used as record separators. The data set is read in Excel. The sample is attached.

**Comment by tiagoCuervo** [comment]
All you need is to have your data as a numpy array. Take a look at [this](https://stackoverflow.com/a/3519314l), it says how you can get a numpy array from your CSV file. You would have to modify the file `mackey.py` to use your data instead.

**Comment by feyzazeynep** [comment]
@eugenpar Were you able to modify the code? I am also looking for a similar solution.
