### ISSUE TITLE
Adapt this code to my data

### ISSUE THREAD

**Issue by sebducos** [tiagoCuervo/FuzzyTensor#5]
Hi,

I'm trying to adapt your code to my data but i think i am missing something.
Even with simple data like : 
inputs : [1, 2, 3, 4], [5, 6, 7, 8]
output : [100], [200]
The results are really bad. I saw that data had to be standardized, but what is the rule? Can you give me an example?
Attached used files.

Thank you in advance.

[files.zip](https://github.com/tiagoCuervo/TensorANFIS/files/4878151/files.zip)

**Comment by tiagoCuervo** [comment]
Hi! Yes, the algorithm expects the data to be roughly in the interval [-1, 1], so the data should be normalized to have mean 0 and standard deviation of 1.0. All you need to do is substract the mean and divide by the standard deviation. Check [this answer](https://stackoverflow.com/questions/31152967/normalise-2d-numpy-array-zero-mean-unit-variance) in stackoverflow. If you use numbers as large as 100 and 200 in your example, the algorithm won't converge or would do so but very slowly (depending on the learning rate).

I just tried the code with the simple data that you used but adapting it to the interval [-1, 1]:

`trnData = [[.1, .2, .3, .4], [.5, .6, .7, .8]]`
`trnLbls = [.1, .2]`

And it works fine, after 100 epochs it gives as result:

`[[0.09865985]
 [0.20008259]]`
